---
title: "R Notebook"
output: html_notebook
---

Load functions

```{r}
source('imgw.R', encoding = 'UTF-8')
library(data.table)
```

Create a list of Mondays

```{r}
poniedzialki<-lista_poniedzialkow(do=as.POSIXct("2017-08-14"))
```

Alternatively, create a list of days
```{r}
dni<-lista_dni(od=as.POSIXct("2017-07-01"), do=as.POSIXct("2017-08-119"))
```

Load newest temperature data

```{r}
zakres<-153:154
baza=bazaHist
temp_min_new<-sciagaj_liste(p_temp_min, poniedzialki[zakres], baza)
temp_avg_new<-sciagaj_liste(p_temp_avg, poniedzialki[zakres], baza)
temp_max_new<-sciagaj_liste(p_temp_max, poniedzialki[zakres], baza)
print(paste(nrow(temp_min_new), nrow(temp_avg_new), nrow(temp_max_new)))

```
```{r}
baza=bazaO
temp_min_new<-sciagaj_liste(p_temp_min, dni[1:11], baza, zakres='/doba/')
temp_avg_new<-sciagaj_liste(p_temp_avg, dni[1:11], baza, zakres='/doba/')
temp_max_new<-sciagaj_liste(p_temp_max, dni[1:11], baza, zakres='/doba/')
print(paste(nrow(temp_min_new), nrow(temp_avg_new), nrow(temp_max_new)))

```

Merge temperature data

```{r}
temp_minavg<-merge(temp_min_new[,1:2], temp_avg_new[,1:2], by="data")
temp_all<-merge(temp_minavg, temp_max_new[,1:2], by="data")
rm(temp_minavg)
colnames(temp_all)<-c("Data", "temp_min", "temp_avg", "temp_max")
temp_all[,Data:=as.character(as.Date(Data))]
temperatura<-rbind(temperatura, temp_all)

```

Save temperature file

```{r}
write.csv(temperatura, file = "IMGW_temp_20170630.csv", fileEncoding = 'UTF-8')

```

Load newest rain&snow data

```{r}
zakres<-153:154
baza=bazaO
deszcz_new<-sciagaj_liste(p_deszcz_doba, poniedzialki[zakres], baza)
snieg_new<-sciagaj_liste(p_snieg_doba, poniedzialki[zakres], baza)
print(paste(nrow(deszcz_new), nrow(snieg_new)))

```

Merge new rain&snow data

```{r}
opady_nowe<-merge(deszcz_new[,1:2], snieg_new[,1:2], by="data")
opady_nowe[is.na(opady_nowe)]<-0
colnames(opady_nowe)<-c("Data", "deszcz", "snieg")
opady_nowe[,Data:=as.character(as.Date(Data))]

```


```{r}
opady<-rbind(opady, opady_nowe)

```

Save rain&snow file

```{r}
write.csv(opady, file = "IMGW_opady_20170630.csv", fileEncoding = 'UTF-8')

```

Load clouds data
```{r}
zakres<-149:153
chmury_new<-sciagaj_liste(p_zachmurzenie_godz, poniedzialki[zakres], bazaHist)
print(nrow(chmury_new))

```

```{r}
chmury<-rbind(chmury, chmury_new)
```

```{r}
write.csv(chmury, file = "IMGW_chmury_20170630.csv", fileEncoding = 'UTF-8')

```

Load wind data
```{r}
zakres<-149:153
wiatr_new<-sciagaj_liste(p_wiatr_godz, poniedzialki[zakres], bazaHist)
print(nrow(wiatr_new))

```

```{r}
wiatr<-rbind(wiatr, wiatr_new)
```

```{r}
write.csv(wiatr, file = "IMGW_wiatr_20170630.csv", fileEncoding = 'UTF-8')

```

