---
title: "R Notebook"
output: html_notebook
---

Load stuff

```{r}
library(data.table)
source('ladowanie_danych.R', encoding = 'UTF-8')
source('obsluga_sumowania.R', encoding = 'UTF-8')
source('pogoda/imgw.R', encoding = 'UTF-8')
```

```{r}
miasto="Kraków" #Krak%C3%B3w
katalog="pliki_Krakow"
plik_pogoda=paste(katalog, "IMGW_pogoda_20181031.csv", sep="/")
plik_polozenie=paste(katalog,"polozenie_licznikow.csv", sep="/")
plik_style=paste(katalog, "listy_stylow.csv", sep="/")
plik_dane_long=paste(katalog, "dane_long.csv", sep="/")
dane_polaczone=paste("dane", miasto, "dane_polaczone.csv", sep="/")
dane_z_pogoda=paste("dane",miasto,"dane_zsumowane_z_pogoda.csv")
```

```{r add new weather}
plik_pogoda_old=paste(katalog, "IMGW_pogoda_20180930.csv", sep="/")
pogoda_old<-fread(plik_pogoda_old)
pogoda_old[,Data:=as.Date(Data)]
pogoda_new<-czytaj_dane_zipy(od=10, do=10, stacja = krakowBalice)
pogoda_new[,opad:=NULL]
pogoda_new[,rodzaj:=NULL]

pogoda<-unique(rbind(pogoda_old, pogoda_new))
write.csv(pogoda, file = plik_pogoda, fileEncoding = 'UTF-8', row.names = F)

```

```{r}
metadane<-wczytaj_metadane_z_api(credentials, miasto=miasto)
print(head(metadane))

lokacje<-zrob_sumy(metadane)
write.csv(lokacje, plik_polozenie, row.names = F, fileEncoding = 'UTF-8')
```

```{r}
lokacje<-data.table(read.csv(plik_polozenie, encoding='UTF-8'))
klucz <- lokacje[,c("id", "Miejsce")]
```

```{r listy stylow - tylko prz nowych licznikach}
listy_stylow<-zrob_listy_stylow(lokacje, paleta=paleta30) #w obsluga_sumowania
write.csv(listy_stylow, file = plik_style, fileEncoding = 'UTF-8', row.names = F)
```

```{r sciagaj dane z api}
dane<-wczytaj_z_api(credentials, klucz=klucz, od="2014-08-13", do="2018-11-01", miasto)
dane<-numery_dat(dane)
write.csv(dane, file = dane_polaczone, fileEncoding = 'UTF-8')
```


```{r sumuj dane i dodaj pogode}
dane_zsumowane<-suma_licznikow(dane)
dane_zsumowane<-dodaj_pogode(dane_zsumowane, plik_pogoda)
write.csv(dane_zsumowane, file = dane_z_pogoda, fileEncoding = 'UTF-8')
dane_long<-wide_to_long(dane_zsumowane)
write.csv(dane_long, file = plik_dane_long, fileEncoding = 'UTF-8')
rm(dane)
rm(dane_zsumowane)
```
